name: Git Flow Finish Release/Hotfix

on:
  push:
    branches:
      - main

jobs:
  finish-release-or-hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: ""

      - name: Merge main → develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
